import type { HeroRecord } from "./types";

export const heroes: HeroRecord[] = [
  {
    id: "symmetra",
    name: "秩序之光",
    englishName: "SYMMETRA",
    role: "输出",
    archetype: "空间控制 / 战术位移",
    debutDate: "2016-05-24",
    accent: "#18a9b7",
    quote: "真正的秩序，需要不断校准。",
    changes: [
      {
        id: "sym-2016-12-13",
        date: "2016-12-13",
        patchLabel: "第一次英雄重做",
        kind: "rework",
        title: "从护盾支援转向阵地构筑",
        summary: "加入移动屏障与护盾发生器，传送面板耐久结构重新分配。",
        details: ["传送面板生命：200 → 50", "传送面板护盾：0 → 350", "哨戒炮携带数量：3 → 6"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2016/12/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2018-06-26",
        date: "2018-06-26",
        patchLabel: "秩序之光 3.0",
        kind: "rework",
        title: "转为输出英雄",
        summary: "武器、炮台、传送面板与终极技能全部重做，形成当前玩法骨架。",
        details: ["主射击取消自动锁定", "每级伤害充能：1 秒 → 2 秒", "弹药：100 → 70", "可部署炮台：6 → 3", "副射击不再穿透"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2018/06/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2018-08-09",
        date: "2018-08-09",
        patchLabel: "射程调整",
        kind: "buff",
        title: "主射击更容易维持",
        summary: "光子发射器主射击射程由 10 米提高至 12 米。",
        details: ["主射击射程：10m → 12m"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2018/08/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2018-11-13",
        date: "2018-11-13",
        patchLabel: "光束强化",
        kind: "buff",
        title: "光束充能加快",
        summary: "主射击光束提升伤害等级的速度加快 20%。",
        details: ["主射击充能速度：+20%"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2018/11/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-03-19",
        date: "2019-03-19",
        patchLabel: "护甲规则变更",
        kind: "system",
        title: "光束对护甲效率下降",
        summary: "护甲开始对主射击与哨戒炮的光束类伤害提供 20% 减伤。",
        details: ["光束对护甲伤害：−20%", "同时影响主射击与哨戒炮"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/03/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-03-19-ramp",
        date: "2019-03-19",
        patchLabel: "光束充能补偿",
        kind: "buff",
        title: "主射击升档速度提高",
        summary: "同一版本中，官方还让主射击伤害升档加快 20%，用于补偿光束对护甲效率下降。",
        details: ["主射击伤害升档速度：+20%", "与护甲规则削弱发生在同一版本"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/03/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-04-16",
        date: "2019-04-16",
        patchLabel: "传送面板放置优化",
        kind: "buff",
        title: "可穿过可破坏栏杆放置",
        summary: "栏杆等可破坏物不再阻止传送面板放置和传送，减少了地图几何导致的失败。",
        details: ["可破坏栏杆不再阻挡放置", "可破坏物不再阻挡传送判定"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/04/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-06-18",
        date: "2019-06-18",
        patchLabel: "传送交互范围",
        kind: "buff",
        title: "使用传送门更宽容",
        summary: "英雄与传送面板的互动距离提高，解决落点稍远时无法使用的问题。",
        details: ["交互距离：1m → 1.5m"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/06/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-08-13",
        date: "2019-08-13",
        patchLabel: "永久传送面板",
        kind: "nerf",
        title: "无限持续换来重新部署能力下降",
        summary: "传送面板改为永久存在并扩大射程，但冷却只有在面板被摧毁后才开始；对固定阵地是增强，对频繁换点属于明显削弱。",
        details: ["持续时间：10s → 无限，直至摧毁", "最大距离：25m → 30m", "冷却起点：放置时 → 被摧毁时", "可主动摧毁传送面板", "入口与出口距离超过 40m 时自动摧毁"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/08/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-09-17",
        date: "2019-09-17",
        patchLabel: "伤害回调",
        kind: "nerf",
        title: "光束宽度与伤害降低",
        summary: "三级光束伤害与命中宽容度同时下降。",
        details: ["光束宽度：0.3m → 0.2m", "DPS：65/130/195 → 60/120/180"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/09/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-09-24",
        date: "2019-09-24",
        patchLabel: "地形放置规则回滚",
        kind: "system",
        title: "传送面板边缘吸附规则撤回",
        summary: "撤回一周前地面目标技能更偏向边缘放置的全局规则，传送面板的落点判定随之恢复。",
        details: ["撤回地面目标技能的边缘优先放置规则", "同时影响暗影步、冰墙等地面技能"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/09/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2019-10-15",
        date: "2019-10-15",
        patchLabel: "阵地能力削弱",
        kind: "nerf",
        title: "屏障与炮台同步降温",
        summary: "光子屏障持续时间、耐久以及哨戒炮伤害均被降低。",
        details: ["屏障持续：15s → 12s", "屏障生命：5000 → 4000", "炮台 DPS：50 → 40"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2019/10/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2020-02-12",
        date: "2020-02-12",
        patchLabel: "副射击增强",
        kind: "buff",
        title: "蓄力球伤害提高",
        summary: "提高副射击最大蓄力伤害；该正式平衡适用于 PC。",
        details: ["副射击：120 → 140"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2020/02/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
        platform: "PC / 全平台",
        platformScope: "all",
      },
      {
        id: "sym-2020-02-12-console",
        date: "2020-02-12",
        patchLabel: "主机独立平衡",
        kind: "nerf",
        title: "主机版炮台伤害再次降低",
        summary: "仅主机平台的哨戒炮伤害调整；默认 PC 档案不会显示或统计这条记录。",
        details: ["主机炮台 DPS：34 → 30"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2020/02/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
        platform: "仅主机",
        platformScope: "console",
      },
      {
        id: "sym-2020-08-13",
        date: "2020-08-13",
        patchLabel: "传送冷却缩短",
        kind: "buff",
        title: "重新部署等待时间减少",
        summary: "官方降低永久传送面板被摧毁后的冷却，缓解个人机动与团队运输之间的冲突。",
        details: ["传送面板冷却：12s → 10s"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2020/08/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2020-08-31",
        date: "2020-08-31",
        patchLabel: "伤害压缩",
        kind: "nerf",
        title: "副射击伤害回调",
        summary: "最大蓄力球伤害回到 120，护甲对光束的减伤同时提高。",
        details: ["副射击最大伤害：140 → 120", "护甲对光束减伤：20% → 30%"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2020/08/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2020-10-29",
        date: "2020-10-29",
        patchLabel: "基础护盾提升",
        kind: "buff",
        title: "自身护盾生命提高",
        summary: "秩序之光的基础护盾增加，提高了近距离维持光束时的生存能力。",
        details: ["基础护盾：100 → 125", "当时总生命：200 → 225"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2020/10/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2020-11-19",
        date: "2020-11-19",
        patchLabel: "死亡后传送控制",
        kind: "buff",
        title: "阵亡时也能主动拆除传送面板",
        summary: "阵亡等待复活期间可以销毁旧传送面板，让冷却更早开始并准备下一次部署。",
        details: ["阵亡状态下可主动摧毁传送面板"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2020/11/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2021-04-01-april-fools",
        date: "2021-04-01",
        patchLabel: "四月娱乐实验卡",
        kind: "buff",
        track: "arcade",
        title: "娱乐版本：光束射程延长",
        summary: "四月娱乐实验卡把主射击光束射程大幅延长；这不是正式核心平衡，也不会计入正式增强统计。",
        details: ["主射击光束射程：12m → 16m", "官方说明：四月娱乐实验", "状态：限时实验卡"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/experimental/2021/04/",
        sourceLabel: "暴雪官方四月实验补丁",
        sourceKind: "official",
        platform: "限时娱乐 · 未上线",
      },
      {
        id: "sym-2021-06-22",
        date: "2021-06-22",
        patchLabel: "跨平台统一",
        kind: "buff",
        title: "主机炮台取消伤害惩罚",
        summary: "跨平台联机上线后，主机版哨戒炮不再造成较低伤害。",
        details: ["主机与 PC 炮台伤害统一"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2021/06/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
        platform: "主机",
        platformScope: "console",
      },
      {
        id: "sym-2021-11-30-creator-cup",
        date: "2021-11-30",
        patchLabel: "创作者杯实验卡",
        kind: "buff",
        track: "experimental",
        title: "创作者杯：通过传送面板后加速",
        summary: "为创作者杯准备的限时实验方案，让传送面板兼具团队加速功能；与正式服历史分开保存。",
        details: ["通过传送面板后获得 50% 移速", "加速持续：1.5s", "后续追加：哨戒炮上限提高至 4 座"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/experimental/2021/11/",
        sourceLabel: "暴雪官方创作者实验补丁",
        sourceKind: "official",
        platform: "创作者杯实验卡 · 未上线",
      },
      {
        id: "sym-2022-02-18-experimental",
        date: "2022-02-18",
        patchLabel: "辅助英雄实验卡",
        kind: "rework",
        track: "experimental",
        title: "未上线的辅助定位传送方案",
        summary: "实验卡把秩序之光改为辅助英雄；传送面板冷却增加，但队友通过后获得短时移速。该方案未进入正式服。",
        details: ["传送面板冷却：10s → 12s", "队友通过后获得 40% 移速，持续 2s", "同一队友的移速效果冷却：10s"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/experimental/2022/02/",
        sourceLabel: "暴雪官方实验补丁",
        sourceKind: "official",
        platform: "实验模式（未上线）",
      },
      {
        id: "sym-2022-06-28",
        date: "2022-06-28",
        patchLabel: "《守望先锋 2》Beta",
        kind: "rework",
        track: "experimental",
        title: "5v5 环境适配",
        summary: "传送面板部署更快，但持续时间、耐久和冷却受到限制；副射击伤害下降。",
        details: ["副射击伤害：120 → 90", "传送面板冷却：10s → 16s", "传送面板生命：300 → 200", "炮台减速：20% → 15%"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/beta/2022/06/",
        sourceLabel: "暴雪官方 Beta 补丁",
        sourceKind: "official",
        platform: "Beta",
      },
      {
        id: "sym-2022-12-06",
        date: "2022-12-06",
        patchLabel: "光束节奏调整",
        kind: "rework",
        title: "充能更快，消耗也更高",
        summary: "提升光束充能速度并恢复攻击屏障补弹，但弹药消耗和衰减速度增加。",
        details: ["充能与衰减速度：+20%", "耗弹：7/s → 10/s", "攻击屏障恢复弹药"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2022/12/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2023-02-07",
        date: "2023-02-07",
        patchLabel: "终极技能调整",
        kind: "nerf",
        title: "光子屏障充能变慢",
        summary: "光子屏障终极技能消耗提高 10%。",
        details: ["终极技能消耗：+10%"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2023/02/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2023-07-11",
        date: "2023-07-11",
        patchLabel: "炮台功能转换",
        kind: "rework",
        title: "炮台由伤害转向侦察",
        summary: "大幅降低炮台伤害，换取敌人显形；副射击伤害和护盾恢复获得加强。",
        details: ["炮台 DPS：40 → 25", "副射击：90 → 100", "炮台命中时显形敌人"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2023/07/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2023-10-31",
        date: "2023-10-31",
        patchLabel: "生存能力回调",
        kind: "nerf",
        title: "总生命降低至 200",
        summary: "远程副射击变强后，官方降低了她的近距离生存能力。",
        details: ["基础护盾：125 → 100", "总生命：225 → 200"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2023/10/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2024-02-13",
        date: "2024-02-13",
        patchLabel: "第 9 赛季全局调整",
        kind: "system",
        title: "生命池扩张改变击杀阈值",
        summary: "多数英雄增加 50 生命，100 伤害副射击通常由两发击杀变为三发。",
        details: ["秩序之光总生命：200 → 250", "多数目标总生命：200 → 250", "全体终极技能消耗：+10%"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2024/02/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2024-03-12",
        date: "2024-03-12",
        patchLabel: "季中强化",
        kind: "buff",
        title: "全套数值强化",
        summary: "光束、炮台和传送面板均获得提升。",
        details: ["主射击 DPS：60/120/180 → 65/130/195", "炮台生命：30 → 50", "炮台 DPS：25 → 30", "传送面板总耐久：200 → 300"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2024/03/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2024-03-19",
        date: "2024-03-19",
        patchLabel: "快速回调",
        kind: "nerf",
        title: "一周后撤回主要强化",
        summary: "光束伤害恢复原值，炮台生命降低，但仍高于强化前。",
        details: ["主射击 DPS：65/130/195 → 60/120/180", "炮台生命：50 → 40"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2024/03/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2024-06-20",
        date: "2024-06-20",
        patchLabel: "近距离定位强化",
        kind: "buff",
        title: "生命与光束启动速度提升",
        summary: "强化近距离存活能力，让光束更快进入高伤害阶段。",
        details: ["基础生命：100 → 125", "总生命：250 → 275", "主射击充能速度：+25%"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2024/06/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2024-12-10",
        date: "2024-12-10",
        patchLabel: "团队传送强化",
        kind: "buff",
        title: "传送面板更难被摧毁",
        summary: "官方希望增强围绕传送面板的团队协作，因此提高其护盾耐久。",
        details: ["传送面板护盾：200 → 250"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2024/12/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2025-02-18",
        date: "2025-02-18",
        patchLabel: "英雄威能上线",
        kind: "buff",
        track: "perk",
        title: "获得四项可选威能",
        summary: "炮台容量、传送距离、光束射程与护盾恢复获得新的成长方向。",
        details: ["哨戒炮额外获得 1 次充能", "传送距离：+50%", "光束射程随等级增加", "传送面板附近恢复护盾"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2025/2/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2025-08-26",
        date: "2025-08-26",
        patchLabel: "威能重组",
        kind: "rework",
        track: "perk",
        title: "传送射程威能移除",
        summary: "移除高级传送，降低完美校准的射程收益，同时加入移动屏障威能。",
        details: ["Advanced Teleportation：移除", "Perfect Alignment：最高 45% → 固定 20%", "新增 Hovering Barrier"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2025/08/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2026-01-08",
        date: "2026-01-08",
        patchLabel: "精度与反制调整",
        kind: "nerf",
        title: "副射击弹体与传送耐久降低",
        summary: "远程命中要求提高，传送面板也更容易被集火摧毁。",
        details: ["副射击弹体：0.5m → 0.4m", "传送面板护盾：250 → 200"],
        sourceUrl: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2026/01/",
        sourceLabel: "暴雪官方补丁",
        sourceKind: "official",
      },
      {
        id: "sym-2026-06-30-community-crafted",
        date: "2026-06-30",
        patchLabel: "社区共创限时模式",
        kind: "rework",
        track: "arcade",
        title: "社区共创：传送面板团队增益实验",
        summary: "仅适用于 2026 年 6 月 30 日至 7 月 13 日的 Community Crafted 限时街机模式，不是正式核心或常规威能改动。",
        details: ["原主要威能 Shield Battery（护盾电池）在该限时模式中移入基础技能", "该模式中护盾电池作用于传送面板附近所有盟友，并适用于所有生命类型", "该模式新增主要威能 Acceleporter：盟友通过传送面板后获得 30% 移速，持续 2 秒", "该模式中哨戒炮部署前可在飞行途中攻击敌人"],
        sourceUrl: "https://overwatch.blizzard.com/en-gb/news/patch-notes/live/2026/06/#patch-2026-06-30",
        sourceLabel: "暴雪官方 Community Crafted 限时模式补丁",
        sourceKind: "official",
        platform: "限时娱乐：Community Crafted",
      },
    ],
  },
];
